## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('processing', ['core'])
    module.includes = '.'
    module.source = [
        'model/program.cc',
        'model/taskscheduler.cc',
        'model/thread.cc',
        'model/hwmodel.cc',
        'model/peu.cc',
        'model/sharedresource.cc',
        'model/membus.cc',
        'model/interrupt-controller.cc',
        'model/execenv.cc',
        'model/execenv-helper.cc',
        'model/condition.cc',
        'model/sem.cc',
        'model/local-state-variable.cc',
        'model/local-state-variable-queue.cc',

        # OYSTEDAL
        'model/rrscheduler.cc',
        'model/sync.cc',
        # 'model/apic.cc',
        # 'model/rrpriorityscheduler.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'processing'
    headers.source = [
        'model/program.h',
        'model/taskscheduler.h',
        'model/thread.h',
        'model/hwmodel.h',
        'model/peu.h',
        'model/sharedresource.h',
        'model/membus.h',
        'model/interrupt-controller.h',
        'model/execenv.h',
        'model/execenv-helper.h',
        'model/condition.h',
        'model/sem.h',
        'model/local-state-variable.h',
        'model/local-state-variable-queue.h',

        # OYSTEDAL
        'model/rrscheduler.h',
        'model/sync.h',
        # 'model/apic.h',
        # 'model/rrpriorityscheduler.h',
    ]
