## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('message', ['core'])
    module.source = [
        'model/external-ns3-message.cc',
        'model/raw-data-message.cc',
        'model/cc2420-messages.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'message'
    headers.source = [
        'model/external-ns3-message.h',
        'model/raw-data-message.h',
        'model/cc2420-messages.h',
        ]

   #bld.ns3_python_bindings()
