# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

#def build(bld):
#    obj = bld.create_ns3_program('telosb-example', ['telosb', 'wifi', 'cc2420', 'applications', 'message', 'csma', 'internet', 'processing'#])
#    obj.source = 'telosb-example.cc'

