# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('telosb-example', ['wifi', 'cc2420', 'applications', 'message', 'processing', 'dcep'])
    obj.source = 'telosb-example.cc'
    obj = bld.create_ns3_program('telosb-experiments', ['wifi', 'cc2420', 'applications', 'message', 'processing', 'dcep'])
    obj.source = 'telosb-experiments.cc'
