# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    pass
    #obj = bld.create_ns3_program('telosb-example', ['wifi', 'cc2420', 'applications', 'message', 'processing'])
    #obj.source = 'telosb-example.cc'
